platform :ios, '12.0'
inhibit_all_warnings!

target 'AimyboxExample' do
  use_frameworks!

  pod 'Aimybox/Core', :path => '~/Documents/Projects/aimybox-ios-sdk'
  pod 'Aimybox/Utils', :path => '~/Documents/Projects/aimybox-ios-sdk'
  pod 'Aimybox/YandexSpeechKit', :path => '~/Documents/Projects/aimybox-ios-sdk'
 
 
  pod 'SDWebImage'
  pod 'SwiftLint'

end

