platform :ios, '12.0'
inhibit_all_warnings!

install! 'cocoapods',
         :deterministic_uuids => false

target 'AimyboxExample' do
  use_frameworks!

  pod 'Aimybox/Core', :path => '../'
  pod 'Aimybox/Utils', :path => '../'
  pod 'Aimybox/AimyboxDialogAPI', :path => '../'
  pod 'Aimybox/YandexSpeechKit', :path => '../'
 
 
  pod 'SDWebImage'
  pod 'SwiftLint'

end

