//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: yandex/cloud/ai/tts/v3/tts_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// A set of methods for voice synthesis.
///
/// Usage: instantiate `Speechkit_Tts_V3_SynthesizerClient`, then call methods of this protocol to make API calls.
internal protocol Speechkit_Tts_V3_SynthesizerClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Speechkit_Tts_V3_SynthesizerClientInterceptorFactoryProtocol? { get }

  func utteranceSynthesis(
    _ request: Speechkit_Tts_V3_UtteranceSynthesisRequest,
    callOptions: CallOptions?,
    handler: @escaping (Speechkit_Tts_V3_UtteranceSynthesisResponse) -> Void
  ) -> ServerStreamingCall<Speechkit_Tts_V3_UtteranceSynthesisRequest, Speechkit_Tts_V3_UtteranceSynthesisResponse>
}

extension Speechkit_Tts_V3_SynthesizerClientProtocol {
  internal var serviceName: String {
    return "speechkit.tts.v3.Synthesizer"
  }

  /// Synthesizing text into speech.
  ///
  /// - Parameters:
  ///   - request: Request to send to UtteranceSynthesis.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func utteranceSynthesis(
    _ request: Speechkit_Tts_V3_UtteranceSynthesisRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Speechkit_Tts_V3_UtteranceSynthesisResponse) -> Void
  ) -> ServerStreamingCall<Speechkit_Tts_V3_UtteranceSynthesisRequest, Speechkit_Tts_V3_UtteranceSynthesisResponse> {
    return self.makeServerStreamingCall(
      path: "/speechkit.tts.v3.Synthesizer/UtteranceSynthesis",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUtteranceSynthesisInterceptors() ?? [],
      handler: handler
    )
  }
}

internal protocol Speechkit_Tts_V3_SynthesizerClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'utteranceSynthesis'.
  func makeUtteranceSynthesisInterceptors() -> [ClientInterceptor<Speechkit_Tts_V3_UtteranceSynthesisRequest, Speechkit_Tts_V3_UtteranceSynthesisResponse>]
}

internal final class Speechkit_Tts_V3_SynthesizerClient: Speechkit_Tts_V3_SynthesizerClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Speechkit_Tts_V3_SynthesizerClientInterceptorFactoryProtocol?

  /// Creates a client for the speechkit.tts.v3.Synthesizer service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Speechkit_Tts_V3_SynthesizerClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// A set of methods for voice synthesis.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Speechkit_Tts_V3_SynthesizerProvider: CallHandlerProvider {
  var interceptors: Speechkit_Tts_V3_SynthesizerServerInterceptorFactoryProtocol? { get }

  /// Synthesizing text into speech.
  func utteranceSynthesis(request: Speechkit_Tts_V3_UtteranceSynthesisRequest, context: StreamingResponseCallContext<Speechkit_Tts_V3_UtteranceSynthesisResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Speechkit_Tts_V3_SynthesizerProvider {
  internal var serviceName: Substring { return "speechkit.tts.v3.Synthesizer" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "UtteranceSynthesis":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Speechkit_Tts_V3_UtteranceSynthesisRequest>(),
        responseSerializer: ProtobufSerializer<Speechkit_Tts_V3_UtteranceSynthesisResponse>(),
        interceptors: self.interceptors?.makeUtteranceSynthesisInterceptors() ?? [],
        userFunction: self.utteranceSynthesis(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Speechkit_Tts_V3_SynthesizerServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'utteranceSynthesis'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUtteranceSynthesisInterceptors() -> [ServerInterceptor<Speechkit_Tts_V3_UtteranceSynthesisRequest, Speechkit_Tts_V3_UtteranceSynthesisResponse>]
}
